//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPedidos.Domain.Exceptions.Clientes {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientesExceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestaoPedidos.Domain.Exceptions.Clientes.ClientesExceptions", typeof(ClientesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente foi ativado com sucesso.
        /// </summary>
        public static string Cliente_ativado {
            get {
                return ResourceManager.GetString("Cliente_ativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cpf informado ja existe .
        /// </summary>
        public static string Cliente_CpfExistente {
            get {
                return ResourceManager.GetString("Cliente_CpfExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cpf precisa ter 11 digitos .
        /// </summary>
        public static string Cliente_CpfInvalido {
            get {
                return ResourceManager.GetString("Cliente_CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cpf do cliente é obrigatório!.
        /// </summary>
        public static string Cliente_CpfObrigatorio {
            get {
                return ResourceManager.GetString("Cliente_CpfObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email informado ja esta cadastrado, escolha outro !.
        /// </summary>
        public static string Cliente_EmailExistente {
            get {
                return ResourceManager.GetString("Cliente_EmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email esta em um formato invalido.
        /// </summary>
        public static string Cliente_EmailInvalido {
            get {
                return ResourceManager.GetString("Cliente_EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email do cliente é obrigatório!.
        /// </summary>
        public static string Cliente_EmailObrigatorio {
            get {
                return ResourceManager.GetString("Cliente_EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O id do cliente é obrigatório.
        /// </summary>
        public static string Cliente_IdObrigatorio {
            get {
                return ResourceManager.GetString("Cliente_IdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente foi inativado com sucesso .
        /// </summary>
        public static string Cliente_Inativado {
            get {
                return ResourceManager.GetString("Cliente_Inativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente esta inativo.
        /// </summary>
        public static string Cliente_Inativo {
            get {
                return ResourceManager.GetString("Cliente_Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente ja esta ativo .
        /// </summary>
        public static string Cliente_JaAtivo {
            get {
                return ResourceManager.GetString("Cliente_JaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente ja está inativo.
        /// </summary>
        public static string Cliente_JaInativo {
            get {
                return ResourceManager.GetString("Cliente_JaInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente não foi encontrado .
        /// </summary>
        public static string Cliente_NaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do cliente é obrigatório!.
        /// </summary>
        public static string Cliente_NomeObrigatorio {
            get {
                return ResourceManager.GetString("Cliente_NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Telefone do cliente é obrigatório!.
        /// </summary>
        public static string Cliente_TelefoneObrigatório {
            get {
                return ResourceManager.GetString("Cliente_TelefoneObrigatório", resourceCulture);
            }
        }
    }
}
